# Generated by Django 4.2.5 on 2024-02-24 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_basemodel'),
        ('propertyStatus', '0006_project_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('questions', models.CharField(blank=True, max_length=100)),
                ('answer', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('project_faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
