# Generated by Django 4.2.4 on 2024-02-09 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('project_name', models.CharField(max_length=100)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('status_name', models.CharField(max_length=100)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='TaxType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('tax_type', models.CharField(max_length=100)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='UnitNo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('unit_no', models.CharField(max_length=100)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('property_type', models.CharField(max_length=100)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('phase_name', models.CharField(max_length=100)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
            ],
            bases=('account.basemodel',),
        ),
    ]
