# Generated by Django 4.2.4 on 2024-02-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitno',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unitno',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
