# Generated by Django 5.0.1 on 2024-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0002_unitno_available_unitno_booked'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitno',
            name='hold',
            field=models.BooleanField(default=False),
        ),
    ]
