# Generated by Django 5.0.1 on 2024-02-11 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0003_unitno_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxtype',
            name='tax_percent',
            field=models.IntegerField(default=0),
        ),
    ]
