# Generated by Django 4.2.5 on 2024-02-16 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0004_taxtype_tax_percent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Statuses'},
        ),
        migrations.RemoveField(
            model_name='phase',
            name='projects',
        ),
        migrations.AddField(
            model_name='phase',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno'),
        ),
    ]
