# Generated by Django 4.2.5 on 2024-02-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0005_alter_status_options_remove_phase_projects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
