# Generated by Django 4.2.5 on 2024-03-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0006_project_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitno',
            name='east_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unitno',
            name='north_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unitno',
            name='south_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unitno',
            name='unit_cost',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='unitno',
            name='west_by',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
