# Generated by Django 4.2.5 on 2024-03-06 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0007_unitno_east_by_unitno_north_by_unitno_south_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitno',
            name='square_fit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
