# Generated by Django 4.2.5 on 2024-03-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        ('propertyStatus', '0008_unitno_square_fit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocumentType',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('document_of', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('date', models.DateField()),
                ('document_file', models.FileField(upload_to='')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projectdocumenttype')),
                ('project_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
            ],
            bases=('account.basemodel',),
        ),
    ]
