# Generated by Django 4.2.5 on 2024-03-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0009_projectdocumenttype_projectdocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectdocument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='projectdocument',
            name='document_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
