# Generated by Django 4.2.5 on 2024-05-15 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0011_phase_projects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitno',
            name='unit_cost',
            field=models.IntegerField(null=True),
        ),
    ]
