# Generated by Django 4.2.5 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0014_remove_project_ecternal_electric_charges_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ecternal_electric_charges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='maintaince_charges_2_year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='mutation_charges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='society_charges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='water_connection_charges',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
