# Generated by Django 4.2.5 on 2024-06-11 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0015_project_ecternal_electric_charges_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='ecternal_electric_charges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='maintaince_charges_2_year',
        ),
        migrations.RemoveField(
            model_name='project',
            name='mutation_charges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='society_charges',
        ),
        migrations.RemoveField(
            model_name='project',
            name='water_connection_charges',
        ),
    ]
