# Generated by Django 4.2.5 on 2024-05-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userholiday_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='normal_user',
            field=models.BooleanField(default=False),
        ),
    ]
