# Generated by Django 4.2.5 on 2024-05-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_normal_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assign',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
