# Generated by Django 4.2.5 on 2024-06-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_assign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
