# Generated by Django 4.2.5 on 2024-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_basemodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_booking_form',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_clinet_loan_profile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_demand_letter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_direct_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_documentation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_payment_stages',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_project_document',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_property_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='account_report',
            field=models.BooleanField(default=False),
        ),
    ]
