# Generated by Django 4.2.5 on 2024-06-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_user_account_billing_user_account_booking_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sales_add_new_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_corporate_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_dump_data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_my_job_desk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_site_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='sales_view_lead',
            field=models.BooleanField(default=False),
        ),
    ]
