# Generated by Django 4.2.5 on 2024-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_basemodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accounts_all_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='accounts_customer_details',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='accounts_registry_details',
            field=models.BooleanField(default=False),
        ),
    ]
