# Generated by Django 4.2.5 on 2024-04-07 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('account', '0007_alter_userholiday_user'),
        ('sendEmails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmailtoclients',
            name='all_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MailTemplate',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('mail', models.TextField(blank=True, null=True)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
            ],
            bases=('account.basemodel',),
        ),
    ]
