# Generated by Django 4.2.5 on 2024-04-07 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('sendEmails', '0002_sendmailtoclients_all_projects_mailtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailtemplate',
            name='all_projects',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mailtemplate',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype'),
        ),
        migrations.AddField(
            model_name='sendmailtoclients',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype'),
        ),
    ]
