# Generated by Django 4.2.5 on 2024-03-22 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0004_remove_user_role_user_accounts_employee_user_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('description', tinymce.models.HTMLField()),
                ('projec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
