# Generated by Django 4.2.5 on 2024-03-22 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sendwhatsappmessage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappmessage',
            old_name='projec',
            new_name='project_name',
        ),
    ]
