# Generated by Django 4.2.5 on 2024-03-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sendwhatsappmessage', '0003_trackwhatappmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackwhatappmessage',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
