# Generated by Django 4.2.5 on 2024-04-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('sendwhatsappmessage', '0004_alter_trackwhatappmessage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='all_project',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='whatsappmessage',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project'),
        ),
    ]
