# Generated by Django 4.2.5 on 2024-04-06 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('sendwhatsappmessage', '0005_whatsappmessage_all_project_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype'),
        ),
    ]
