# Generated by Django 4.2.5 on 2024-09-06 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('civilWorker', '0025_constructorprofile_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.BigIntegerField(blank=True, null=True)),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('rate', models.BigIntegerField(blank=True, null=True)),
                ('constructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ConstBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_no', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.BigIntegerField(blank=True, null=True)),
                ('total_amount', models.BigIntegerField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.constproject')),
            ],
        ),
    ]
