# Generated by Django 4.2.5 on 2024-09-07 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constbill',
            name='billed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constproject',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
