# Generated by Django 4.2.5 on 2024-09-07 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0026_alter_constructorprofile_unit'),
        ('bills', '0002_constbill_billed_constproject_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsExported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(blank=True, null=True, upload_to='')),
                ('constructor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorprofile')),
            ],
        ),
    ]
