# Generated by Django 4.2.5 on 2024-09-07 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_billsexported_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billsexported',
            name='bill_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='constbill',
            name='prev_total_amount',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
