# Generated by Django 4.2.5 on 2024-02-23 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_basemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingForm', '0004_booking_corner_plot_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientLoanProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_address', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=100)),
                ('loan_file_no', models.CharField(max_length=100)),
                ('loan_date', models.DateField()),
                ('loan_amount_sanctioned', models.CharField(max_length=100)),
                ('excutive_name', models.CharField(max_length=100)),
                ('excutive_number', models.CharField(max_length=100)),
                ('status_active_inactive', models.CharField(max_length=100)),
                ('loan_approval_date', models.DateField()),
                ('margin_amount', models.CharField(max_length=100)),
                ('bookings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingForm.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
