# Generated by Django 4.2.5 on 2024-07-27 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0014_alter_user_is_active'),
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='CivilStatges',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('stage1', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_1', models.BooleanField(default=False)),
                ('target_date_stage_1', models.DateField(blank=True, null=True)),
                ('completed_date_stage_1', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_1', models.BooleanField(default=False)),
                ('percentage_stage_1', models.FloatField(default=10)),
                ('stage2', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_2', models.BooleanField(default=False)),
                ('target_date_stage_2', models.DateField(blank=True, null=True)),
                ('completed_date_stage_2', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_2', models.BooleanField(default=False)),
                ('percentage_stage_2', models.FloatField(default=10)),
                ('stage3', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_3', models.BooleanField(default=False)),
                ('target_date_stage_3', models.DateField(blank=True, null=True)),
                ('completed_date_stage_3', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_3', models.BooleanField(default=False)),
                ('percentage_stage_3', models.FloatField(default=10)),
                ('stage4', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_4', models.BooleanField(default=False)),
                ('target_date_stage_4', models.DateField(blank=True, null=True)),
                ('completed_date_stage_4', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_4', models.BooleanField(default=False)),
                ('percentage_stage_4', models.FloatField(default=10)),
                ('stage5', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_5', models.BooleanField(default=False)),
                ('target_date_stage_5', models.DateField(blank=True, null=True)),
                ('completed_date_stage_5', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_5', models.BooleanField(default=False)),
                ('percentage_stage_5', models.FloatField(default=10)),
                ('stage6', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_6', models.BooleanField(default=False)),
                ('target_date_stage_6', models.DateField(blank=True, null=True)),
                ('completed_date_stage_6', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_6', models.BooleanField(default=False)),
                ('percentage_stage_6', models.FloatField(default=10)),
                ('stage7', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_7', models.BooleanField(default=False)),
                ('target_date_stage_7', models.DateField(blank=True, null=True)),
                ('completed_date_stage_7', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_7', models.BooleanField(default=False)),
                ('percentage_stage_7', models.FloatField(default=10)),
                ('stage8', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_8', models.BooleanField(default=False)),
                ('target_date_stage_8', models.DateField(blank=True, null=True)),
                ('completed_date_stage_8', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_8', models.BooleanField(default=False)),
                ('percentage_stage_8', models.FloatField(default=10)),
                ('stage9', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_9', models.BooleanField(default=False)),
                ('target_date_stage_9', models.DateField(blank=True, null=True)),
                ('completed_date_stage_9', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_9', models.BooleanField(default=False)),
                ('percentage_stage_9', models.FloatField(default=10)),
                ('stage10', models.CharField(blank=True, max_length=100, null=True)),
                ('completed_stage_10', models.BooleanField(default=False)),
                ('target_date_stage_10', models.DateField(blank=True, null=True)),
                ('completed_date_stage_10', models.DateField(blank=True, null=True)),
                ('completed_before_hand_stage_10', models.BooleanField(default=False)),
                ('percentage_stage_10', models.FloatField(default=10)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.bills')),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='Miscellaneous',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='ConstructorProfile',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('rate', models.FloatField(blank=True, null=True)),
                ('civil_statge', models.ManyToManyField(blank=True, to='civilWorker.civilstatges')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='miscellaneous_expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.miscellaneous'),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='remark',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.remarks'),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno'),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
