# Generated by Django 4.2.5 on 2024-07-27 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/bills/'),
        ),
    ]
