# Generated by Django 4.2.5 on 2024-07-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0002_alter_bills_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='constructorprofile',
            old_name='company_name',
            new_name='bank_name',
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='bank_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='discount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='gst',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='hsncode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='ifsc_code',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
