# Generated by Django 4.2.5 on 2024-07-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0003_rename_company_name_constructorprofile_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorprofile',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
