# Generated by Django 4.2.5 on 2024-07-27 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0004_alter_constructorprofile_ifsc_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='miscellaneous',
            name='delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remarks',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
