# Generated by Django 4.2.5 on 2024-07-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0005_bills_delete_civilstatges_delete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
