# Generated by Django 4.2.5 on 2024-07-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
        ('civilWorker', '0006_constructorprofile_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructorprofile',
            name='civil_statge',
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='constructor_profile',
            field=models.ManyToManyField(blank=True, to='civilWorker.constructorprofile'),
        ),
        migrations.AddField(
            model_name='constructorprofile',
            name='unit',
            field=models.ManyToManyField(blank=True, to='propertyStatus.unitno'),
        ),
    ]
