# Generated by Django 4.2.5 on 2024-07-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0007_remove_constructorprofile_civil_statge_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilstatges',
            name='constructor_profile',
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='constructor_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorprofile'),
        ),
    ]
