# Generated by Django 4.2.5 on 2024-07-29 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
        ('account', '0015_user_platform'),
        ('civilWorker', '0008_remove_civilstatges_constructor_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelFilesCivilStages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('prev_bill', models.JSONField(blank=True, null=True)),
                ('constructor_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorprofile')),
                ('unit', models.ManyToManyField(blank=True, to='propertyStatus.unitno')),
            ],
            bases=('account.basemodel',),
        ),
    ]
