# Generated by Django 4.2.5 on 2024-08-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0010_invoicecivilstages'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilstatges',
            name='completed_date_stage_11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='completed_stage_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='percentage_stage_11',
            field=models.FloatField(default=5),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='stage11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='target_date_stage_11',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_5',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_7',
            field=models.FloatField(default=15),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_9',
            field=models.FloatField(default=5),
        ),
    ]
