# Generated by Django 4.2.5 on 2024-08-02 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0011_civilstatges_completed_date_stage_11_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfilescivilstages',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
