# Generated by Django 4.2.5 on 2024-08-02 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0012_excelfilescivilstages_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicecivilstages',
            name='bill_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
