# Generated by Django 4.2.5 on 2024-08-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0013_invoicecivilstages_bill_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilstatges',
            name='completed_before_hand_stage_11',
            field=models.BooleanField(default=False),
        ),
    ]
