# Generated by Django 4.2.5 on 2024-08-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0014_civilstatges_completed_before_hand_stage_11'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilstatges',
            name='stage1',
            field=models.CharField(blank=True, default='Piles', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage10',
            field=models.CharField(blank=True, default='Pre Final', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage11',
            field=models.CharField(blank=True, default='Hand over', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage2',
            field=models.CharField(blank=True, default='Plinth', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage3',
            field=models.CharField(blank=True, default='GF Slab', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage4',
            field=models.CharField(blank=True, default='Piles', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage5',
            field=models.CharField(blank=True, default='Tower/Mummty', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage6',
            field=models.CharField(blank=True, default='Brick Work', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage7',
            field=models.CharField(blank=True, default='Plastring', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage8',
            field=models.CharField(blank=True, default='Flooring', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='stage9',
            field=models.CharField(blank=True, default='Double Coat Putty & Double Coat Putty', max_length=100, null=True),
        ),
    ]
