# Generated by Django 4.2.5 on 2024-08-02 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0015_alter_civilstatges_stage1_alter_civilstatges_stage10_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilstatges',
            name='stage4',
            field=models.CharField(blank=True, default='FF Slab', max_length=100, null=True),
        ),
    ]
