# Generated by Django 4.2.5 on 2024-08-04 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_basemodel_updated_at'),
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
        ('civilWorker', '0016_alter_civilstatges_stage4'),
    ]

    operations = [
        migrations.CreateModel(
            name='COnstructorUnitNo',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('unit_no', models.CharField(max_length=100)),
                ('available', models.BooleanField(default=False)),
                ('booked', models.BooleanField(default=False)),
                ('hold', models.BooleanField(default=False)),
                ('east_by', models.CharField(blank=True, max_length=100)),
                ('west_by', models.CharField(blank=True, max_length=100)),
                ('north_by', models.CharField(blank=True, max_length=100)),
                ('south_by', models.CharField(blank=True, max_length=100)),
                ('unit_cost', models.IntegerField(null=True)),
                ('square_fit', models.CharField(blank=True, max_length=100, null=True)),
                ('delete', models.BooleanField(default=False)),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
            ],
            bases=('account.basemodel',),
        ),
        migrations.AlterField(
            model_name='bills',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorunitno'),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorunitno'),
        ),
        migrations.AlterField(
            model_name='constructorprofile',
            name='unit',
            field=models.ManyToManyField(blank=True, to='civilWorker.constructorunitno'),
        ),
        migrations.AlterField(
            model_name='excelfilescivilstages',
            name='unit',
            field=models.ManyToManyField(blank=True, to='civilWorker.constructorunitno'),
        ),
        migrations.AlterField(
            model_name='invoicecivilstages',
            name='unit',
            field=models.ManyToManyField(blank=True, to='civilWorker.constructorunitno'),
        ),
        migrations.AlterField(
            model_name='miscellaneous',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorunitno'),
        ),
        migrations.AlterField(
            model_name='remarks',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='civilWorker.constructorunitno'),
        ),
    ]
