# Generated by Django 4.2.5 on 2024-08-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0017_constructorunitno_alter_bills_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_10',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_11',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_6',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_7',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_8',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='updated_percentage_stage_9',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
