# Generated by Django 4.2.5 on 2024-08-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0018_civilstatges_updated_percentage_stage_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorunitno',
            name='rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
