# Generated by Django 4.2.5 on 2024-08-04 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0019_constructorunitno_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='civilstatges',
            name='miscellaneous_expense',
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='miscellaneous_expense',
            field=models.ManyToManyField(blank=True, to='civilWorker.miscellaneous'),
        ),
    ]
