# Generated by Django 4.2.5 on 2024-08-09 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0020_remove_civilstatges_miscellaneous_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='excelfilescivilstages',
            name='downloaded_sucessfully',
            field=models.BooleanField(default=False),
        ),
    ]
