# Generated by Django 4.2.5 on 2024-08-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0021_excelfilescivilstages_downloaded_sucessfully'),
    ]

    operations = [
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_10',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_11',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_8',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='civilstatges',
            name='bill_downloaded_9',
            field=models.BooleanField(default=False),
        ),
    ]
