# Generated by Django 4.2.5 on 2024-08-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0022_civilstatges_bill_downloaded_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_1',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_10',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_11',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_2',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_3',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_4',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_5',
            field=models.FloatField(default=5, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_6',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_7',
            field=models.FloatField(default=15, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_8',
            field=models.FloatField(default=10, null=True),
        ),
        migrations.AlterField(
            model_name='civilstatges',
            name='percentage_stage_9',
            field=models.FloatField(default=5, null=True),
        ),
    ]
