# Generated by Django 4.2.5 on 2024-08-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0023_alter_civilstatges_percentage_stage_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='miscellaneous',
            name='prev_bill',
            field=models.BooleanField(default=False),
        ),
    ]
