# Generated by Django 4.2.5 on 2024-09-06 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0024_miscellaneous_prev_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructorprofile',
            name='profile',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
