# Generated by Django 4.2.5 on 2024-09-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('civilWorker', '0025_constructorprofile_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructorprofile',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, to='civilWorker.constructorunitno'),
        ),
    ]
