# Generated by Django 4.2.4 on 2024-02-09 04:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0003_basemodel'),
        ('propertyStatus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('tax_percent', models.CharField(blank=True, max_length=100)),
                ('unit_cost', models.CharField(blank=True, max_length=100)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('interst_rate', models.CharField(blank=True, max_length=100)),
                ('Annual_income', models.CharField(blank=True, max_length=100)),
                ('east_by', models.CharField(blank=True, max_length=100)),
                ('west_by', models.CharField(blank=True, max_length=100)),
                ('north_by', models.CharField(blank=True, max_length=100)),
                ('south_by', models.CharField(blank=True, max_length=100)),
                ('booking_amount', models.CharField(blank=True, max_length=100)),
                ('application_date', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=100)),
                ('loan_required', models.CharField(max_length=100)),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
                ('tax_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.taxtype')),
                ('type_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype')),
                ('unit_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='CoApplicantForm',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('present_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('residence_address', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('adhar_no', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('fax_number', models.CharField(max_length=100)),
                ('matial_status', models.CharField(max_length=100)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='PersonalDeatils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100)),
                ('so_wo_do', models.CharField(max_length=100)),
                ('persent_address', models.CharField(max_length=100)),
                ('permanent_address', models.CharField(max_length=100)),
                ('pin_code', models.CharField(max_length=100)),
                ('date_of_birth', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('mobile_number', models.CharField(max_length=100)),
                ('residence_address', models.CharField(max_length=100)),
                ('email_address', models.CharField(max_length=100)),
                ('adhar_no', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('pan_number', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('fax_number', models.CharField(max_length=100)),
                ('matial_status', models.CharField(max_length=100)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingForm.booking')),
            ],
        ),
    ]
