# Generated by Django 4.2.4 on 2024-02-09 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0002_coapplicantform_user_personaldeatils_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personaldeatils',
            options={'verbose_name_plural': 'Personal Details'},
        ),
        migrations.AddField(
            model_name='coapplicantform',
            name='personal_deatils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.personaldeatils'),
        ),
    ]
