# Generated by Django 5.0.1 on 2024-02-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0003_alter_personaldeatils_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='corner_plot_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='cost_payable_to_company',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='discount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='external_electrical_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='govt_extra_charges',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='booking',
            name='maintainance_charges_2_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='mutation_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='other_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='park_face_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='registry_extra_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='socity_maintaince_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='water_connection_charges',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking',
            name='wide_road_facing_charges',
            field=models.IntegerField(default=0),
        ),
    ]
