# Generated by Django 4.2.5 on 2024-03-05 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        ('bookingForm', '0004_booking_corner_plot_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllDocument',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('document', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.RemoveField(
            model_name='booking',
            name='east_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='north_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='south_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='west_by',
        ),
        migrations.AddField(
            model_name='booking',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='mutation_True_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='mutation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='posession_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='posession_true_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='registry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='registry_true_false',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='document_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.alldocument'),
        ),
    ]
