# Generated by Django 4.2.5 on 2024-03-05 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0005_alldocument_remove_booking_east_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='document',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='document_name',
        ),
        migrations.AddField(
            model_name='personaldeatils',
            name='document',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='personaldeatils',
            name='document_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.alldocument'),
        ),
    ]
