# Generated by Django 4.2.5 on 2024-03-11 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0008_unitno_square_fit'),
        ('bookingForm', '0006_remove_booking_document_remove_booking_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tax_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.taxtype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unit_no',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno'),
        ),
    ]
