# Generated by Django 4.2.5 on 2024-03-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0007_alter_booking_project_name_alter_booking_tax_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='tax_percent',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
