# Generated by Django 4.2.5 on 2024-03-18 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0009_alter_booking_gender_alter_booking_loan_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='loan_required',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=100, null=True),
        ),
    ]
