# Generated by Django 4.2.5 on 2024-03-20 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0010_alter_booking_loan_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldeatils',
            name='so_wo_do',
            field=models.CharField(choices=[('S/O', 'S/O'), ('W/O', 'W/O'), ('D/O', 'D/O')], max_length=100),
        ),
    ]
