# Generated by Django 4.2.5 on 2024-03-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0011_alter_personaldeatils_so_wo_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldeatils',
            name='so_wo_do',
            field=models.CharField(max_length=100),
        ),
    ]
