# Generated by Django 4.2.5 on 2024-03-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0012_alter_personaldeatils_so_wo_do'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldeatils',
            name='adhar_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='age',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='applicant_name',
            field=models.CharField(blank=True, choices=[('S/O', 'S/O'), ('W/O', 'W/O'), ('D/O', 'D/O')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.booking'),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='date_of_birth',
            field=models.DateField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='email_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='fax_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='matial_status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='pan_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='permanent_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='persent_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='pin_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='profession',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='residence_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='so_wo_do',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
