# Generated by Django 4.2.5 on 2024-03-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0013_alter_personaldeatils_adhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldeatils',
            name='applicant_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personaldeatils',
            name='so_wo_do',
            field=models.CharField(blank=True, choices=[('S/O', 'S/O'), ('W/O', 'W/O'), ('D/O', 'D/O')], max_length=100, null=True),
        ),
    ]
