# Generated by Django 4.2.5 on 2024-04-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0015_alter_coapplicantform_adhar_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='cost_payable_to_company',
            field=models.FloatField(default=0),
        ),
    ]
