# Generated by Django 4.2.5 on 2024-04-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0016_alter_booking_cost_payable_to_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='unit_cost',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
