# Generated by Django 4.2.5 on 2024-04-30 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0017_alter_booking_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldeatils',
            name='sowodo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
