# Generated by Django 4.2.5 on 2024-05-15 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0018_personaldeatils_sowodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='govt_extra_charges',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
