# Generated by Django 4.2.5 on 2024-05-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0019_alter_booking_govt_extra_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_amount',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
