# Generated by Django 4.2.5 on 2024-05-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0022_alter_booking_booking_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='govt_extra_charges',
            field=models.IntegerField(default=0),
        ),
    ]
