# Generated by Django 4.2.5 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0023_alter_booking_govt_extra_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coapplicantform',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldeatils',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
