# Generated by Django 4.2.5 on 2024-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0024_booking_deleted_coapplicantform_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coapplicantform',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personaldeatils',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
