# Generated by Django 4.2.5 on 2024-11-19 23:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
        ('bookingForm', '0025_booking_cancelled_coapplicantform_cancelled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('cancellation_date', models.DateTimeField(auto_now_add=True)),
                ('total_refund_amt', models.FloatField(blank=True, default=0, null=True)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('remaining_bal', models.FloatField(blank=True, default=0, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.booking')),
                ('unit_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
            ],
        ),
        migrations.CreateModel(
            name='CancelRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refunded_amt', models.FloatField(default=0)),
                ('mode_of_refund', models.CharField(max_length=100)),
                ('cheque_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('cancelbooking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.cancelbooking')),
            ],
        ),
    ]
