# Generated by Django 4.2.5 on 2024-11-20 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0026_cancelbooking_cancelrefund'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelrefund',
            name='reciept_no',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
