# Generated by Django 4.2.5 on 2024-11-25 21:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0027_cancelrefund_reciept_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancelrefund',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
