# Generated by Django 4.2.5 on 2024-11-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0028_cancelrefund_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cancelrefund',
            name='mode_of_refund',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
