# Generated by Django 4.2.5 on 2024-03-05 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('propertyStatus', '0007_unitno_east_by_unitno_north_by_unitno_south_by_and_more'),
        ('profileSearch', '0011_remove_paymentstagedetail_advance_amount_and_more'),
        ('account', '0003_basemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeOfPayment',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('mode_of_payment', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='account.basemodel')),
                ('receipt_id', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('receipt_date', models.DateField()),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documentation.modeofpayment')),
                ('payment_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileSearch.paymentstagedetail')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
                ('unit_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='DemandLetter',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('payment_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileSearch.paymentstagedetail')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
                ('unit_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
            ],
            bases=('account.basemodel',),
        ),
    ]
