# Generated by Django 4.2.5 on 2024-03-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        ('documentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankNameBranchName',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('branch_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.AddField(
            model_name='receipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='drawn_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='branch_name_bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.banknamebranchname'),
        ),
    ]
