# Generated by Django 4.2.5 on 2024-03-06 05:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0008_unitno_square_fit'),
        ('documentation', '0003_demandletter_user_receipt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandletter',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='project_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype'),
        ),
        migrations.AddField(
            model_name='demandletter',
            name='tax_percentage',
            field=models.DateField(blank=True, null=True),
        ),
    ]
