# Generated by Django 4.2.5 on 2024-03-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0004_demandletter_date_demandletter_project_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandletter',
            name='tax_percentage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
