# Generated by Django 4.2.5 on 2024-03-06 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        ('documentation', '0005_alter_demandletter_tax_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankName',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('bank_name', models.CharField(max_length=100)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='branch_name_bank_name',
        ),
        migrations.AddField(
            model_name='receipt',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='BankNameBranchName',
        ),
        migrations.AddField(
            model_name='receipt',
            name='bank_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='documentation.bankname'),
        ),
    ]
