# Generated by Django 4.2.5 on 2024-03-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0006_bankname_remove_receipt_branch_name_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_id',
            field=models.AutoField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
