# Generated by Django 4.2.5 on 2024-03-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0007_alter_receipt_receipt_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='basemodel_ptr',
        ),
    ]
