# Generated by Django 4.2.5 on 2024-03-12 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        ('documentation', '0008_remove_receipt_basemodel_ptr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='receipt_id',
        ),
        migrations.AddField(
            model_name='receipt',
            name='basemodel_ptr',
            field=models.OneToOneField(auto_created=True, default=1200, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel'),
            preserve_default=False,
        ),
    ]
