# Generated by Django 4.2.5 on 2024-03-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0009_remove_receipt_receipt_id_receipt_basemodel_ptr'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_unique_id',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True),
        ),
    ]
