# Generated by Django 4.2.5 on 2024-03-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0010_receipt_receipt_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='drawn_on',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='transation_id',
        ),
        migrations.AddField(
            model_name='bankname',
            name='drawn_on',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
