# Generated by Django 4.2.5 on 2024-04-06 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0011_remove_receipt_drawn_on_remove_receipt_transation_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='receipt_unique_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
