# Generated by Django 4.2.5 on 2024-05-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0012_alter_receipt_receipt_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cancel',
            field=models.BooleanField(default=False),
        ),
    ]
