# Generated by Django 4.2.5 on 2024-05-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0013_receipt_cancel'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='delete',
            field=models.BooleanField(default=False),
        ),
    ]
