# Generated by Django 4.2.5 on 2024-05-23 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0014_receipt_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='by_bank',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='by_customer',
            field=models.BooleanField(default=False),
        ),
    ]
