# Generated by Django 4.2.5 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0015_receipt_by_bank_receipt_by_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandletter',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='receipt',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
