# Generated by Django 4.2.5 on 2024-11-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0016_demandletter_deleted_receipt_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
