# Generated by Django 4.2.5 on 2024-11-26 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentation', '0017_receipt_cancelled'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandletter',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
