# Generated by Django 5.0.1 on 2024-02-11 12:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0003_basemodel'),
        ('bookingForm', '0004_booking_corner_plot_charges_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('stage_name', models.CharField(blank=True, max_length=100)),
                ('personal_deatils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingForm.personaldeatils')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='PaymentStageDetail',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('step', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('demand_date', models.DateField(blank=True, null=True)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('advance_amount', models.FloatField(default=0)),
                ('due_amount', models.FloatField(default=0)),
                ('amount_to_be_paid', models.FloatField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileSearch.paymentstages')),
            ],
            bases=('account.basemodel',),
        ),
    ]
