# Generated by Django 5.0.1 on 2024-02-11 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0002_paymentreceipts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentreceipts',
            old_name='stage',
            new_name='stage_deatils',
        ),
    ]
