# Generated by Django 5.0.1 on 2024-02-11 17:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        ('profileSearch', '0003_rename_stage_paymentreceipts_stage_deatils'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemiderDemandInformation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('deplay', models.CharField(blank=True, max_length=100)),
                ('interst', models.FloatField(default=0)),
                ('amount_to_be_paid', models.FloatField(default=0)),
                ('stage_deatils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileSearch.paymentstagedetail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
    ]
