# Generated by Django 5.0.1 on 2024-02-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0004_remiderdemandinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remiderdemandinformation',
            old_name='stage_deatils',
            new_name='payment_receipts_stage',
        ),
    ]
