# Generated by Django 5.0.1 on 2024-02-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0005_rename_stage_deatils_remiderdemandinformation_payment_receipts_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remiderdemandinformation',
            name='payment_receipts_stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileSearch.paymentreceipts'),
        ),
    ]
