# Generated by Django 4.2.5 on 2024-02-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0006_alter_remiderdemandinformation_payment_receipts_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentstages',
            options={'verbose_name': 'Payment Status', 'verbose_name_plural': 'Payment Statuses'},
        ),
    ]
