# Generated by Django 4.2.5 on 2024-02-16 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0004_booking_corner_plot_charges_and_more'),
        ('profileSearch', '0007_alter_paymentstages_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='stage',
        ),
        migrations.AddField(
            model_name='paymentstagedetail',
            name='personal_deatils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.personaldeatils'),
        ),
        migrations.AddField(
            model_name='paymentstagedetail',
            name='stage_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='PaymentStages',
        ),
    ]