# Generated by Django 4.2.5 on 2024-02-18 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookingForm', '0004_booking_corner_plot_charges_and_more'),
        ('profileSearch', '0008_remove_paymentstagedetail_stage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='personal_deatils',
        ),
        migrations.CreateModel(
            name='PaymentStages',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('stage_name', models.CharField(blank=True, max_length=100)),
                ('personal_deatils', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingForm.personaldeatils')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Status',
                'verbose_name_plural': 'Payment Statuses',
            },
            bases=('account.basemodel',),
        ),
        migrations.AlterField(
            model_name='paymentstagedetail',
            name='stage_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profileSearch.paymentstages'),
        ),
    ]
