# Generated by Django 4.2.5 on 2024-02-24 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingForm', '0004_booking_corner_plot_charges_and_more'),
        ('profileSearch', '0009_remove_paymentstagedetail_personal_deatils_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentstagedetail',
            old_name='date',
            new_name='payable_date',
        ),
        migrations.RenameField(
            model_name='paymentstagedetail',
            old_name='amount',
            new_name='step_no',
        ),
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='step',
        ),
        migrations.AddField(
            model_name='paymentstagedetail',
            name='paybale_amount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paymentstagedetail',
            name='personal_deatils',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingForm.personaldeatils'),
        ),
        migrations.AlterField(
            model_name='paymentstagedetail',
            name='advance_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstagedetail',
            name='amount_to_be_paid',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstagedetail',
            name='due_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='paymentstagedetail',
            name='stage_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='PaymentStages',
        ),
    ]
