# Generated by Django 4.2.5 on 2024-02-24 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0010_rename_date_paymentstagedetail_payable_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='advance_amount',
        ),
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='amount_to_be_paid',
        ),
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='demand_date',
        ),
        migrations.RemoveField(
            model_name='paymentstagedetail',
            name='due_amount',
        ),
    ]
