# Generated by Django 4.2.5 on 2024-06-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0011_remove_paymentstagedetail_advance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipts',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentstagedetail',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remiderdemandinformation',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
