# Generated by Django 4.2.5 on 2024-11-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileSearch', '0012_paymentreceipts_deleted_paymentstagedetail_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentstagedetail',
            name='cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
