# Generated by Django 4.2.5 on 2024-03-05 17:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FbLeads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.today, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('Source', models.CharField(blank=True, max_length=255, null=True)),
                ('Form', models.CharField(blank=True, max_length=255, null=True)),
                ('Channel', models.CharField(blank=True, max_length=255, null=True)),
                ('Stage', models.CharField(blank=True, max_length=255, null=True)),
                ('Owner', models.CharField(blank=True, max_length=255, null=True)),
                ('Labels', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
