# Generated by Django 4.2.5 on 2024-03-09 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='phone',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
