# Generated by Django 4.2.5 on 2024-03-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_fbleads_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbleads',
            old_name='created_on',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='Channel',
            new_name='form_id',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='Labels',
            new_name='form_name',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='Owner',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='Source',
            new_name='job_title',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='Stage',
            new_name='page_id',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='name',
            new_name='page_name',
        ),
        migrations.RenameField(
            model_name='fbleads',
            old_name='phone',
            new_name='phone_number',
        ),
        migrations.AddField(
            model_name='fbleads',
            name='ad_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='ad_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='adset_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='adset_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='campaign_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='city',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='custom_disclaimer_responses',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='partner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='platform',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='select_available_price',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
