# Generated by Django 4.2.5 on 2024-03-13 04:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_rename_created_on_fbleads_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
