# Generated by Django 4.2.5 on 2024-03-13 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_basemodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('social', '0005_fbleads_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('max_budget', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('feedback_of_client', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='LeadSource',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('lead_source', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='MediumOfLead',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('medium', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.CreateModel(
            name='preferredLocation',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('preferred_location', models.CharField(blank=True, max_length=100, null=True)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='alternative_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='AddNewLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=18, null=True)),
                ('alternative_number', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('budget', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.budget')),
                ('by_medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.mediumoflead')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.feedback')),
                ('lead_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.leadsource')),
                ('phase_name', models.ManyToManyField(blank=True, to='propertyStatus.phase')),
                ('preferred_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.preferredlocation')),
                ('project_name', models.ManyToManyField(blank=True, to='propertyStatus.project')),
                ('project_type_name', models.ManyToManyField(blank=True, to='propertyStatus.projecttype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
