# Generated by Django 4.2.5 on 2024-03-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('social', '0009_leadedit_user_modelead_user_statuslead_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fbleads',
            old_name='Form',
            new_name='form',
        ),
        migrations.AddField(
            model_name='fbleads',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.budget'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='by_medium',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.mediumoflead'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.feedback'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='lead_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.leadsource'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='occupation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='phase_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.phase'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='preferred_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.preferredlocation'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.project'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project_type_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.projecttype'),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='fb_leads',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.fbleads'),
        ),
        migrations.DeleteModel(
            name='AddNewLead',
        ),
    ]
