# Generated by Django 4.2.5 on 2024-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_rename_form_fbleads_form_fbleads_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='dump_lead',
            field=models.BooleanField(default=False),
        ),
    ]
