# Generated by Django 4.2.5 on 2024-03-15 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_fbleads_dump_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadedit',
            name='enquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
