# Generated by Django 4.2.5 on 2024-03-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_fbleads_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='site_visit',
            field=models.BooleanField(default=False),
        ),
    ]
