# Generated by Django 4.2.5 on 2024-03-18 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_user_role_user_accounts_employee_user_admin_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('social', '0014_fbleads_site_visit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FeedBack',
            new_name='Reason',
        ),
        migrations.RenameField(
            model_name='leadedit',
            old_name='feedback',
            new_name='reason_for_dump',
        ),
        migrations.RenameField(
            model_name='reason',
            old_name='feedback_of_client',
            new_name='reason_of_client',
        ),
        migrations.AddField(
            model_name='fbleads',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='date_of_booking',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='mobile_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project'),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='square_fit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='status_of_lead_warm_hot_cold',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='visit_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='visit_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='visited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='VisitedBy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ReasonSiteVisit',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('reason_of_site_visit', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('account.basemodel',),
        ),
        migrations.AddField(
            model_name='leadedit',
            name='reason_for_site_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.reasonsitevisit'),
        ),
    ]
