# Generated by Django 4.2.5 on 2024-03-18 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_rename_feedback_reason_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reason',
            old_name='reason_of_client',
            new_name='reason_of_dump',
        ),
    ]
