# Generated by Django 4.2.5 on 2024-03-18 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0010_alter_projectdocument_date_and_more'),
        ('social', '0016_rename_reason_of_client_reason_reason_of_dump'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbleads',
            name='phase_name',
        ),
        migrations.RemoveField(
            model_name='fbleads',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='fbleads',
            name='project_type_name',
        ),
        migrations.AddField(
            model_name='fbleads',
            name='phase_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.phase'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project_type_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.projecttype'),
        ),
    ]
