# Generated by Django 4.2.5 on 2024-03-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_remove_fbleads_phase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='corporate_visit',
            field=models.BooleanField(default=False),
        ),
    ]
