# Generated by Django 4.2.5 on 2024-03-23 09:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_alter_leadedit_created_at_alter_leadedit_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadedit',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='leadedit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
