# Generated by Django 4.2.5 on 2024-03-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_alter_leadedit_created_at_alter_leadedit_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='intersted',
            field=models.BooleanField(default=False),
        ),
    ]
