# Generated by Django 4.2.5 on 2024-03-24 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_fbleads_intersted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadedit',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='leadedit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
