# Generated by Django 5.0.2 on 2024-03-26 06:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_notificationstore'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstore',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='notificationstore',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
