# Generated by Django 5.0.2 on 2024-03-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0024_notificationstore_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='permanent_dump_lead',
            field=models.BooleanField(default=False),
        ),
    ]
