# Generated by Django 4.2.5 on 2024-04-06 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0025_fbleads_permanent_dump_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadsource',
            name='medium_of_lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.mediumoflead'),
        ),
    ]
