# Generated by Django 4.2.5 on 2024-04-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0026_leadsource_medium_of_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadedit',
            name='site_visits',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
