# Generated by Django 4.2.5 on 2024-04-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0027_leadedit_site_visits'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='corporate_visit_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
