# Generated by Django 4.2.5 on 2024-04-09 20:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0028_fbleads_corporate_visit_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='Bhk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='CallStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='CalledOn',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='CompactLabel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='Duplicate',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='Duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='EmailVerificationStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='FollowupCurrentStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='IntentVerificationStatus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='LeadScore',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='ParentProductDetails',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='PhoneVerificationStatus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='ProdType',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='PropertySnapshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='Query',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='Questionnaire',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='SetIsParentProductTypeResponse',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='Type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='configuration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='interestedin',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='productcode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='producttype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='property',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='property_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='property_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='purpose_of_property',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='rescom',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='responetype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='seller_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='seller_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='service_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
