# Generated by Django 4.2.5 on 2024-04-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0029_fbleads_bhk_fbleads_callstatus_fbleads_calledon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='block_enquiry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='call_not_recevied',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='do_not_call',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='good_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='may_be',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='poor_lead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='re_visit',
            field=models.BooleanField(default=False),
        ),
    ]
