# Generated by Django 4.2.5 on 2024-05-14 12:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0030_fbleads_block_enquiry_fbleads_call_not_recevied_and_more'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='fbleads',
        #     name='company_name',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='fbleads',
        #     name='fb_from',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='fbleads',
        #     name='prices_available',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='fbleads',
        #     name='raw',
        #     field=models.JSONField(blank=True, null=True),
        # ),
        # migrations.AddField(
        #     model_name='fbleads',
        #     name='retailer_item_id',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        # migrations.AddField(
        #     model_name='fbleads',
        #     name='vehicle',
        #     field=models.CharField(blank=True, max_length=100, null=True),
        # ),
        migrations.AddField(
            model_name='leadedit',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='created_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='feedback',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]