# Generated by Django 4.2.5 on 2024-05-15 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0011_phase_projects'),
        ('social', '0031_fbleads_company_name_fbleads_fb_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fbleads',
            name='phase_name',
        ),
        migrations.RemoveField(
            model_name='fbleads',
            name='project_name',
        ),
        migrations.RemoveField(
            model_name='fbleads',
            name='project_type_name',
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.project'),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='project_type_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.projecttype'),
        ),
    ]
