# Generated by Django 4.2.5 on 2024-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0032_remove_fbleads_phase_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='prices_available',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='prices_available',
        #     field=models.JSONField(blank=True),
        # ),
    ]
