# Generated by Django 4.2.5 on 2024-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0033_alter_fbleads_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='fb_from',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
