# Generated by Django 4.2.5 on 2024-05-15 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0034_new_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='raw',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='retailer_item_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='vehicle',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
