# Generated by Django 4.2.5 on 2024-05-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0035_new_cols_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='created_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='prices_available',
        #     field=models.JSONField(blank=True),
        # ),
    ]
