# Generated by Django 4.2.5 on 2024-05-15 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0036_alter_fbleads_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(default=datetime.time(21, 52, 13, 41322)),
        ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='created_time',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='prices_available',
        #     field=models.JSONField(blank=True),
        # ),
    ]
