# Generated by Django 4.2.5 on 2024-05-17 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0039_new_col_data'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='Time',
        #     field=models.TimeField(default=datetime.time(14, 5, 33, 95060)),
        # ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='created_time',
        #     field=models.DateTimeField(auto_now=True, null=True),
        # ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='prices_available',
        #     field=models.JSONField(blank=True),
        # ),
        # migrations.AlterField(
        #     model_name='fbleads',
        #     name='receiveddate',
        #     field=models.DateField(default=datetime.date(2024, 5, 17)),
        # ),
        migrations.AlterField(
            model_name='leadedit',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
