# Generated by Django 4.2.5 on 2024-05-23 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0012_alter_unitno_unit_cost'),
        ('social', '0040_alter_fbleads_time_alter_fbleads_created_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(0, 12, 31, 498141), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='block_enquiry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='booked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='call_not_recevied',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='corporate_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='created_time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='do_not_call',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='dump_lead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='good_lead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='intersted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='may_be',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='permanent_dump_lead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='poor_lead',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='prices_available',
            field=models.JSONField(blank=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='project_name',
            field=models.ManyToManyField(blank=True, null=True, to='propertyStatus.project'),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='project_type_name',
            field=models.ManyToManyField(blank=True, null=True, to='propertyStatus.projecttype'),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='re_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 23), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='site_visit',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
