# Generated by Django 4.2.5 on 2024-05-23 00:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0041_alter_fbleads_time_alter_fbleads_block_enquiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(0, 17, 3, 85311), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='prices_available',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
