# Generated by Django 4.2.5 on 2024-05-25 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0042_alter_fbleads_time_alter_fbleads_prices_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationstore',
            name='seen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
