# Generated by Django 4.2.5 on 2024-05-26 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0043_notificationstore_seen_alter_fbleads_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='preferred_location_other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(12, 19, 40, 705534), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 26), null=True),
        ),
    ]
