# Generated by Django 4.2.5 on 2024-05-27 16:36

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0044_fbleads_preferred_location_other_alter_fbleads_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='corporate_visit_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corporate_visit_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='site_visit_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_visit_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(16, 36, 7, 394975), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 27), null=True),
        ),
    ]
