# Generated by Django 4.2.5 on 2024-05-27 22:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0045_fbleads_corporate_visit_to_fbleads_site_visit_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reason',
            name='booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='dump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='site_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(22, 5, 51, 108231), null=True),
        ),
    ]
