# Generated by Django 4.2.5 on 2024-05-27 23:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0046_reason_booked_reason_dump_reason_site_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='dump',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='user',
        ),
        migrations.AddField(
            model_name='statuslead',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statuslead',
            name='dump',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(23, 3, 30, 13537), null=True),
        ),
    ]
