# Generated by Django 4.2.5 on 2024-05-27 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0047_remove_reason_booked_remove_reason_dump_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='site_visit',
        ),
        migrations.AddField(
            model_name='statuslead',
            name='site_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(23, 6, 4, 110685), null=True),
        ),
    ]
