# Generated by Django 4.2.5 on 2024-05-27 23:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social', '0048_remove_reason_site_visit_statuslead_site_visit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statuslead',
            name='Booked',
        ),
        migrations.RemoveField(
            model_name='statuslead',
            name='dump',
        ),
        migrations.RemoveField(
            model_name='statuslead',
            name='site_visit',
        ),
        migrations.AddField(
            model_name='reason',
            name='Booked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='dump',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='site_visit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reason',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
