# Generated by Django 4.2.5 on 2024-05-28 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0049_remove_statuslead_booked_remove_statuslead_dump_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(8, 59, 2, 905690), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 28), null=True),
        ),
    ]
