# Generated by Django 4.2.5 on 2024-05-28 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0050_alter_fbleads_time_alter_fbleads_receiveddate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reason',
            name='Booked',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='dump',
        ),
        migrations.RemoveField(
            model_name='reason',
            name='site_visit',
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(18, 56, 58, 416713), null=True),
        ),
    ]
