# Generated by Django 4.2.5 on 2024-05-30 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0051_remove_reason_booked_remove_reason_dump_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadedit',
            name='purchased_location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(8, 47, 16, 130014), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 5, 30), null=True),
        ),
    ]
