# Generated by Django 4.2.5 on 2024-05-31 17:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0052_leadedit_purchased_location_alter_fbleads_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadedit',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
