# Generated by Django 4.2.5 on 2024-05-31 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0053_alter_fbleads_time_alter_fbleads_receiveddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadedit',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
