# Generated by Django 4.2.5 on 2024-05-31 17:24

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0054_alter_fbleads_time_alter_fbleads_receiveddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
