# Generated by Django 4.2.5 on 2024-06-23 23:05

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0056_alter_fbleads_time_alter_fbleads_receiveddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='feedback',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
