# Generated by Django 4.2.5 on 2024-06-28 01:26

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0057_alter_fbleads_options_alter_leadedit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='reasons_feedback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='social.reason'),
        ),
    ]
