# Generated by Django 4.2.5 on 2024-07-03 21:16

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0058_alter_fbleads_options_alter_leadedit_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fbleads',
            options={'verbose_name': 'All lead', 'verbose_name_plural': 'All leads'},
        ),
        migrations.AlterModelOptions(
            name='leadedit',
            options={'verbose_name': 'Discussion', 'verbose_name_plural': 'Discussions'},
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(21, 16, 2, 981905), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 7, 3), null=True),
        ),
        migrations.AlterField(
            model_name='leadedit',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
