# Generated by Django 4.2.5 on 2024-07-10 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
        ('social', '0059_alter_fbleads_options_alter_leadedit_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='enquiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        
        migrations.AlterField(
            model_name='fbleads',
            name='project_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.project'),
        ),
        
    ]
