# Generated by Django 4.2.5 on 2024-07-13 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0060_fbleads_enquiry_date_alter_fbleads_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='expected_booking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='feedback_acc_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fbleads',
            name='status_acc_admin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
       
    ]
