# Generated by Django 4.2.5 on 2024-07-15 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0061_fbleads_expected_booking_fbleads_feedback_acc_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadedit',
            name='customer_ref_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
