# Generated by Django 4.2.5 on 2024-07-15 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0062_leadedit_customer_ref_name_alter_fbleads_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fbleads',
            name='expected_booking_date',
            field=models.DateField(blank=True, null=True),
        )
    ]
