# Generated by Django 4.2.5 on 2024-07-15 23:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0063_fbleads_expected_booking_date_alter_fbleads_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leadedit',
            name='customer_ref_name',
        ),
        migrations.AddField(
            model_name='fbleads',
            name='customer_ref_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
       
    ]
