# Generated by Django 4.2.5 on 2024-07-28 12:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propertyStatus', '0016_remove_project_ecternal_electric_charges_and_more'),
        ('social', '0064_remove_leadedit_customer_ref_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='project_type_name',
            field=models.ManyToManyField(blank=True, to='propertyStatus.projecttype'),
        ),
    ]
