# Generated by Django 4.2.5 on 2024-11-19 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0065_alter_fbleads_time_alter_fbleads_project_type_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(22, 32, 50, 319631), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 19), null=True),
        ),
    ]
