# Generated by Django 4.2.5 on 2024-11-19 23:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0066_alter_fbleads_time_alter_fbleads_receiveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(23, 43, 1, 631594), null=True),
        ),
    ]
