# Generated by Django 4.2.5 on 2024-11-23 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0069_alter_fbleads_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(19, 59, 12, 848285), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 23), null=True),
        ),
    ]
