# Generated by Django 4.2.5 on 2024-11-25 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0070_alter_fbleads_time_alter_fbleads_receiveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(21, 22, 44, 552256), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 25), null=True),
        ),
    ]
