# Generated by Django 4.2.5 on 2024-11-26 01:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0071_alter_fbleads_time_alter_fbleads_receiveddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fbleads',
            name='Time',
            field=models.TimeField(blank=True, default=datetime.time(1, 57, 16, 36969), null=True),
        ),
        migrations.AlterField(
            model_name='fbleads',
            name='receiveddate',
            field=models.DateField(blank=True, default=datetime.date(2024, 11, 26), null=True),
        ),
    ]
