# Generated by Django 4.2.5 on 2024-04-30 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_alter_userholiday_user'),
        ('propertyStatus', '0011_phase_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteWorkers',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('stage1', models.BooleanField(default=False)),
                ('stage2', models.BooleanField(default=False)),
                ('stage3', models.BooleanField(default=False)),
                ('stage4', models.BooleanField(default=False)),
                ('stage5', models.BooleanField(default=False)),
                ('stage6', models.BooleanField(default=False)),
                ('stage7', models.BooleanField(default=False)),
                ('stage8', models.BooleanField(default=False)),
                ('project_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.project')),
                ('unit_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='propertyStatus.unitno')),
            ],
            bases=('account.basemodel',),
        ),
    ]
