# Generated by Django 4.2.5 on 2024-05-09 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage1',
            new_name='admin_stage1',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage2',
            new_name='admin_stage2',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage3',
            new_name='admin_stage3',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage4',
            new_name='admin_stage4',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage5',
            new_name='admin_stage5',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage6',
            new_name='admin_stage6',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage7',
            new_name='admin_stage7',
        ),
        migrations.RenameField(
            model_name='siteworkers',
            old_name='stage8',
            new_name='delay_stage1',
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='delay_stage2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='delay_stage3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='delay_stage4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='delay_stage5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='delay_stage6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='delay_stage7',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage3',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage4',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage5',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage6',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_stage7',
            field=models.BooleanField(default=False),
        ),
    ]
