# Generated by Django 4.2.5 on 2024-05-16 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_normal_user'),
        ('workers', '0002_rename_stage1_siteworkers_admin_stage1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyExpense',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='account.basemodel')),
                ('money', models.FloatField(blank=True, null=True)),
                ('siteworker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workers.siteworkers')),
            ],
            bases=('account.basemodel',),
        ),
    ]
