# Generated by Django 4.2.5 on 2024-06-01 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0003_monthlyexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='money_rec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='monthlyexpense',
            name='update_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
