# Generated by Django 4.2.5 on 2024-06-02 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0004_monthlyexpense_money_rec_monthlyexpense_stage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyexpense',
            name='money_rec',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
