# Generated by Django 4.2.5 on 2024-06-02 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0005_alter_monthlyexpense_money_rec'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteworkers',
            name='worker_update_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
