# Generated by Django 4.2.5 on 2024-06-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0006_siteworkers_worker_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyexpense',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
