# Generated by Django 4.2.5 on 2024-07-15 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0007_monthlyexpense_deleted_siteworkers_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteworkers',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='reject',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='stage_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='target',
            field=models.BooleanField(default=False),
        ),
    ]
