# Generated by Django 4.2.5 on 2024-07-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0008_siteworkers_accept_siteworkers_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteworkers',
            old_name='date',
            new_name='admin_target_date',
        ),
        migrations.AddField(
            model_name='siteworkers',
            name='worker_target_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
